version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./server.conf:/etc/nginx/conf.d/default.conf:Z
      - ./location.conf:/etc/nginx/default.d/asyncdb.conf:Z
      - ./ui/dist:/usr/share/nginx/html:Z
    ports:
      - 8080:80
      - 8443:443

  asyncdb:
    image: asyncdb:latest
    container_name: asyncdb
    expose:
      - 8080
