version: '3'
services:
  asyncdb:
    build: .
    container_name: asyncdb
    ports:
      - 8080:80
  etcd:
    image: quay.io/coreos/etcd:v3.5.9
    container_name: etcd
    environment:
      - ETCD_NAME=etcd-node
      - ETCD_DATA_DIR=/etcd-data
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - 2379:2379
    volumes:
      - /tmp/etcd-data:/etcd-data:Z
    command:
      - /usr/local/bin/etcd
