name: Build and Push Docker image

on:
  push:
    branches: [ main, master ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2 

    - name: Login to Amazon ECR
      id: ecr-login
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build Docker image
      run: |
        docker build -t asyncdb:latest .

    - name: Tag Docker image for ECR
      run: |
        IMAGE_URI=${{ steps.ecr-login.outputs.registry }}/asyncdb:latest
        docker tag asyncdb:latest $IMAGE_URI

    - name: Push Docker image to ECR
      run: |
        IMAGE_URI=${{ steps.ecr-login.outputs.registry }}/asyncdb:latest
        docker push $IMAGE_URI

