name: Test

on:
  pull_request:
    branches: [ main, master ]

jobs:

  server:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v7

    - name: Validate, compile, test and memcheck
      run: docker build --target builder .

  ui:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v7

    - name: Lint, test and build the UI
      run: docker build --target ui .
